### ISSUE TITLE
Scenarios are not run when using xUnit.net 2.1

### ISSUE THREAD

**Issue by GraemeBradbury** [adamralph/xbehave.net#271]
**Reproduction steps**
Install xBehave 2.0.0
Upgrade xUnit to 2.1.0

**Description**
On upgrading xunit from 2.0.0 to 2.1.0 all xBehave `[Scenario]` exhibit some/all loss of information depending on test runner used.

Visual Studio runner (VS 2013 Update 5) -> failed to discover any tests.
ReSharper runner (R#9.2 xUnit Runner 2.2.8)-> discovered the method marked with `[Scenario]` but marked it as inconclusive.
NCrunch (2.16.0.13) -> discovered the method marked with `[Scenario]`, ran it correctly, but no longer displayed the individual steps.

Plain xunit `[Fact]` are still discovered.

**Comment by adamralph** [comment]
Woah! Thanks for reporting.

@bradwilson does anything immediately come to mind?

**Comment by bradwilson** [comment]
Nothing off the top of my head...

**Comment by adamralph** [comment]
I've successfully reproduced the problem by upgrading the samples to xunit 2.1 - https://github.com/adamralph/xbehave.net-samples/tree/xunit-2.1

**Comment by adamralph** [comment]
I think I've gotten to the bottom of this. I ran the console runner against the samples with `-diagnostics` and I got:

>   Discovering: Xbehave.Samples.net45.ncrunch (app domain = on [shadow copy], method display = ClassAndMethod)
>    Xbehave.Samples.net45.ncrunch: Exception during discovery:
> System.IO.FileLoadException: Could not load file or assembly 'xunit.execution.desktop, Version=2.0.0.2929, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c' or one of its dependencies. The located assembly's manifest definition does not match the assembly
> reference. (Exception from HRESULT: 0x80131040)
> File name: 'xunit.execution.desktop, Version=2.0.0.2929, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c'
>    at Xbehave.Execution.ScenarioDiscoverer.<Discover>d__0.MoveNext()
>    at Xunit.Sdk.XunitTestFrameworkDiscoverer.FindTestsForMethod(ITestMethod testMethod, Boolean includeSourceInformation, IMessageBus messageBus, ITestFrameworkDiscoveryOptions discoveryOptions) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\XunitTestFrameworkDiscoverer.cs:line 95
>    at Xunit.Sdk.XunitTestFrameworkDiscoverer.FindTestsForType(ITestClass testClass, Boolean includeSourceInformation, IMessageBus messageBus, ITestFrameworkDiscoveryOptions discoveryOptions) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\XunitTestFrameworkDiscoverer.cs:line 108
>    at Xunit.Sdk.TestFrameworkDiscoverer.FindTestsForTypeAndWrapExceptions(ITestClass testClass, Boolean includeSourceInformation, IMessageBus messageBus, ITestFrameworkDiscoveryOptions discoveryOptions) in C:\BuildAgent\work\cb37e9acf085d108\src\xunit.execution\Sdk\Frameworks\TestFrameworkDiscoverer.cs:line 156

This means there is a missing binding redirect for `xunit.execution.desktop`. Now, that makes sense, since, in xunit 2.0, `xunit.execution.desktop` is not referenced. Only in xunit 2.1 is it added as a reference, so NuGet doesn't know that a binding redirect should be added. If I add the binding redirect manually, everything works as expected.

This leads me to believe that any xunit extension built against 2.0 and referencing xunit.execution will be broken by an upgrade to xunit 2.1.

I'm trying to think of the best way out of this...

**Comment by adamralph** [comment]
@GraemeBradbury as a temporary workaround, you can manually add a binding redirect for `xunit.execution.desktop`. NuGet should already be doing this for `xunit.core`.

``` xml
<dependentAssembly>
  <assemblyIdentity name="xunit.execution.desktop" publicKeyToken="8d05b1bb7a6fdb6c" culture="neutral" />
  <bindingRedirect oldVersion="0.0.0.0-2.1.0.3179" newVersion="2.1.0.3179" />
</dependentAssembly>
```

**Comment by adamralph** [comment]
I'm going to push out a 2.0.1 patch ASAP which adds a reference to xunit.extensibility.execution. This should force NuGet to recognise that a binding redirect is required when upgrading xunit from 2.0 to 2.1 and it should fix this problem.

**Comment by adamralph** [comment]
@GraemeBradbury I've just pushed 2.0.1-beta001-build598 to NuGet, can you please try it out to see if it solves the issue?

**Comment by GraemeBradbury** [comment]
Works for me :+1:
:shipit:

**Comment by adamralph** [comment]
Awesome, thanks. 2.0.1 coming up shortly...

**Comment by adamralph** [comment]
https://www.nuget.org/packages/Xbehave/2.0.1
https://github.com/xbehave/xbehave.net/releases/tag/2.0.1

Thanks @GraemeBradbury and @bradwilson for all your help with this.

**Comment by brunobertechini** [comment]
I am having the same issue on TFSBuild for a Test project using xunit, binding redirect did not work.

Build Output

```
C:\Program Files (x86)\MSBuild\12.0\bin\amd64\Microsoft.Common.CurrentVersion.targets (1697): Could not resolve this reference. Could not locate the assembly "xunit.execution.desktop, Version=2.1.0.3179, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
```

Build Log

```
'xunit.core' already has a dependency defined for 'xunit.extensibility.core'.
'xunit.extensibility.execution' already has a dependency defined for 'xunit.extensibility.core'.
```

Cheers

Bruno

**Comment by bradwilson** [comment]
> 'xunit.core' already has a dependency defined for 'xunit.extensibility.core'.

Your NuGet package manager inside Visual Studio is (by now, significantly) out of date and needs to be upgraded.

**Comment by adamralph** [comment]
@brunobertechini the issue you are seeing is not the one that was closed by this issue.

As @bradwilson says, you just have an out of date NuGet client.
